form/urls.py
from django.urls import path

from . import views
app_name = "form"
urlpatterns = [
    path('matkul/P<int:id_nama_matkul>/', views.matkuldetail, name='matkuldetail'),
    path('delete/P<int:delete_id>/', views.delete, name='delete'),
    path('viewpage/', views.viewpage, name='viewpage'),
    path('create/', views.create, name='create'),
    path('', views.index, name='index'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('form/', include('form.urls',namespace = 'form')),
    path('story6/',include('story6.urls',namespace = 'story6')),

]

story6/urls.py
from django.urls import path

from . import views
app_name = "story6"
urlpatterns = [
    path('register/P<int:task_id>/', views.register, name='register'),
    path('delete/P<int:delete_id>/', views.delete, name='delete'),
    path('listKegiatan/', views.listKegiatan, name='listKegiatan'),
    path('tambahKegiatan/', views.tambahKegiatan, name='tambahKegiatan'),
    path('index/', views.index, name='index'),

    # path('', views.index, name='index'),
]

story6/models.py
from django.db import models

# Create your models here.

class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length=100)
    deskripsi = models.CharField(max_length=1000)

    def __str__(self):
        return self.nama_kegiatan

class DaftarOrang(models.Model):
    nama_orang = models.CharField(max_length=100)
    kegiatan = models.ForeignKey(Kegiatan,on_delete=models.CASCADE, null=True,blank=True)

    def __str__(self):
        return self.nama_orang

story6/forms.py
from django import forms

class FormKegiatan(forms.Form):
    nama_kegiatan = forms.CharField(
            label = "Nama Kegiatan",
            max_length = 100,
            widget = forms.TextInput(
                attrs={
                    'class':'form-control',
                }
            )
    )
    deskripsi   = forms.CharField(
        label = "Deskripsi Kegiatan",
        max_length = 1000,
        widget = forms.Textarea(
            attrs={
                'class':'form-control',
            }
        )
    )

class FormOrang(forms.Form):
    nama_orang = forms.CharField(
        label = "Nama Orang",
        max_length = 100,
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
            }
        )
    )

story6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect

# Create your views here.
from .forms import FormKegiatan , FormOrang
from .models import Kegiatan, DaftarOrang


def index(request):
    return render(request,'story6/index.html')


def tambahKegiatan(request):
    form_kegiatan = FormKegiatan()
    if request.method == 'POST':
        form_kegiatan_input = FormKegiatan(request.POST)
        if form_kegiatan_input.is_valid():
            Kegiatan.objects.create(
            nama_kegiatan= form_kegiatan_input.cleaned_data.get('nama_kegiatan'),
        )
        return HttpResponseRedirect("/story6/listKegiatan/")
    context = {
        'page_title_kegiatan':'Add Activity',
        'form_kegiatan':form_kegiatan
    }

    return render(request,'story6/tambahKegiatan.html',context)


def listKegiatan(request):
    kegiatan = Kegiatan.objects.all()
    orang = DaftarOrang.objects.all()
    context = {
        'page_title':'List of Activity',
        'kegiatan':kegiatan,
        'orang': orang,
    }

    return render(request,'story6/listKegiatan.html',context)



def delete(request, delete_id):
    try:
        orang_to_delete = DaftarOrang.objects.filter(id = delete_id)
        orang_to_delete.delete()
        return redirect('story6:listKegiatan')
    except:
        return redirect('story6:listKegiatan')


def register(request, task_id):
    form_orang = FormOrang()

    if request.method == 'POST':
        form_orang_input = FormOrang(request.POST)
        if form_orang_input.is_valid():
            data = form_orang_input.cleaned_data
            orangOrang = DaftarOrang()
            orangOrang.nama_orang = data['nama_orang']
            orangOrang.kegiatan = Kegiatan.objects.get(id=task_id)
            orangOrang.save()
            # Orang.objects.create(
            # nama_orang= form_orang_input.cleaned_data.get('nama_orang'),
            # nama_orang.kegiatan = Kegiatan.objects.get(id=task_id)
            # nama_orang.save()
        # )
        return HttpResponseRedirect("/story6/listKegiatan/")

    context = {
        'page_title':'Whats your name',
        'form_orang':form_orang
    }
    return render(request,'story6/register.html',context)

story6/templates/story6/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid">
    <div class="jumbotron">
        <h1 style="font-family: 'Manuale', serif;" class="display-4">My Activity</h1>
        <p class="lead">Hello, You can add new course or see the list of existing courses
        </p>
        <hr class="my-4">
        <p>If you want to add a new course, choose the Add a course one else choose the other</p>
        <a class="btn btn-primary btn-lg" href="/story6/tambahKegiatan" role="button">Add activity</a>
        <a class="btn btn-primary btn-lg" href="/story6/listKegiatan" role="button">See the list</a>
    </div>

</div>
{% endblock content %}

story6/templates/story6/listKegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% block page_title %}
    {{page_title}}
{% endblock page_title %}
{% endblock meta %}


{% block content %}

<section class="container-fluid ">
    <div style="font-family: 'Manuale', serif;" class="section-title mx-auto text-center mt-5">
        <div class="flex-col">

            <h1>Activity List</h1>

        </div>
        
    </div>

    <div style="font-family: LemonMilk;" class="row w-100 justify-content-center">
        {% for activity in kegiatan %}
        <div class="col-4 m-4 p-4 rounded border">
            <ul class="list-group">
                <li class="list-group-item list-group-item-secondary"> <b> {{ activity.nama_kegiatan }} </b> </li>

                {% for itemorang in orang %}
                {% if itemorang.kegiatan == activity %}
                <li class="list-group-item">
                    <div class="d-flex justify-content-between">
                        {{ itemorang.nama_orang }}
                        
                        <a href="{% url 'story6:delete' itemorang.id %}" class="btn btn-warning">Delete</a>
                        

                    </div>
                </li>
                {% endif %}
                {% endfor %}
            </ul>

            <div style="font-size: .75em;" class="section-title mx-auto text-center my-3">

                <a href="{% url 'story6:register' activity.id %}" class="btnMatkul">
                    <button> Register Yourself!</button>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>

</section>









{% endblock content %}

story6/templates/story6/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% block page_title %}
    {{page_title_kegiatan}}
{% endblock page_title %}
{% endblock meta %}


{% block content %}

<div class="container-fluid" style="text-align:justify;">
    <h1 style="font-family: 'Manuale', serif;">Register</h1>
    <form method="POST">
        {% csrf_token %}
        <table style="font-family: 'Manuale', serif; background-color: #E8E8E8 ;">
            {{form_orang.as_table}}
        </table>
        <table class="center" style="font-family: 'Manuale', serif; background-color: #E8E8E8 ;">
            
            <tbody>
            <td>
                <button type="Submit">Send</button>
            </td>
            </tbody>
        </table>    
    </form>

</div>
{% endblock content %}

story6/templates/story6/tambahKegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% block page_title %}
    {{page_title_kegiatan}}
{% endblock page_title %}
{% endblock meta %}


{% block content %}
<div class="container-fluid" style="text-align:justify;">
    <h1 style="font-family: 'Manuale', serif;">Add Activity</h1>
    <form method="POST">
        {% csrf_token %}
        <table style="font-family: 'Manuale', serif; background-color: #E8E8E8 ;">
            {{form_kegiatan.as_table}}
        </table>
        <table class="center" style="font-family: 'Manuale', serif; background-color: #E8E8E8 ;">
            
            <tbody>
            <td>
                <button type="Submit">Send</button>
            </td>
            </tbody>
        </table>    
    </form>

</div>
{% endblock content %}