form/urls.py
from django.urls import path

from . import views
app_name = "form"
urlpatterns = [
    path('matkul/P<int:id_nama_matkul>/', views.matkuldetail, name='matkuldetail'),
    path('delete/P<int:delete_id>/', views.delete, name='delete'),
    path('viewpage/', views.viewpage, name='viewpage'),
    path('create/', views.create, name='create'),
    path('', views.index, name='index'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutme/', views.aboutme, name='aboutme'),
    path('experience/', views.experience, name='experience'),
    path('contact/', views.contact, name='contact'),
    path('gallery/', views.gallery, name='gallery'),
    path('story1/', views.story1, name='story1'),

    



]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('form/', include('form.urls',namespace = 'form')),
    path('story6/',include('story6.urls',namespace = 'story6')),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <a class="navbar-brand" style="font-weight: 700; font-size:xx-large;" href="#">ABR.</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" href="{% url 'main:home' %}">Home</a>
        <a class="nav-link" href="{% url 'main:aboutme' %}">About Me</a>
        <a class="nav-link" href="{% url 'main:experience' %}">Experience</a>
        <a class="nav-link" href="{% url 'main:contact' %}">Contact</a>
        <a class="nav-link" href="{% url 'main:gallery' %}">Gallery</a>
        <a class="nav-link" href="{% url 'main:story1' %}">Story1</a>
        <a class="nav-link" href="{% url 'form:viewpage' %}">Add course</a>
        <a class="nav-link" href="{% url 'story6:index' %}">Add Activity</a>




      </div>
    </div>
  </nav>
</body>
  {% block content %}
  {% endblock content %}
   <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</html>