form/urls.py
from django.urls import path

from . import views
app_name = "form"
urlpatterns = [
    path('matkul/P<int:id_nama_matkul>/', views.matkuldetail, name='matkuldetail'),
    path('delete/P<int:delete_id>/', views.delete, name='delete'),
    path('viewpage/', views.viewpage, name='viewpage'),
    path('create/', views.create, name='create'),
    path('', views.index, name='index'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('form/', include('form.urls',namespace = 'form')),
    path('story6/',include('story6.urls',namespace = 'story6')),

]

form/models.py
from django.db import models

# Create your models here.

class PostModel(models.Model):
    nama_matkul     = models.CharField(max_length = 50)
    jumlah_sks      = models.IntegerField()
    ruangan         = models.CharField(max_length = 100)
    dosen           = models.CharField(max_length = 100)
    deskripsi       = models.CharField(max_length = 1000, null = True)
    semester_tahun  = models.CharField(max_length = 100)

    published       = models.DateTimeField(auto_now_add = True)
    updated         = models.DateTimeField(auto_now = True)

    def __str__(self):
        return "{}.{}".format(self.id,self.nama_matkul)

form/forms.py
from django import forms

class PostForm(forms.Form):
    nama_matkul = forms.CharField(
        label = "Nama mata kuliah",
        max_length = 100,
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
            }

        )

        )
    jumlah_sks  = forms.IntegerField(
        label = "Jumlah sks",
        widget = forms.NumberInput(
            attrs={
                'class':'form-control',
                'min':'1',
                'max':'6'
            }
        )
    )
    ruangan = forms.CharField(
        label = "Ruangan",
        max_length = 100,
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
            }

        )
        
    )
    dosen   = forms.CharField(
        label = "Nama dosen",
        max_length = 100,
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
            }

        )
    )
    deskripsi   = forms.CharField(
        label = "Deskripsi mata kuliah",
        max_length = 1000,
        widget = forms.Textarea(
            attrs={
                'class':'form-control',
            }
        )
    )
    semester_tahun  = forms.CharField(
        label = "Semester tahun",
        max_length = 100,
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
            }
        )
    )    

form/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect

# Create your views here.
from .forms import PostForm
from .models import PostModel

def index(request):
    posts = PostModel.objects.all()
    context = {
        'page_title':'List of Courses',
        'posts':posts,
    }

    return render(request,'form/index.html',context)

def create(request):
    post_form = PostForm()

    if request.method == 'POST':
        PostModel.objects.create(
            nama_matkul       = request.POST.get('nama_matkul'),
            jumlah_sks        = request.POST.get('jumlah_sks'),
            ruangan    = request.POST.get('ruangan'),
            dosen    = request.POST.get('dosen'),
            deskripsi    = request.POST.get('deskripsi'),
            semester_tahun    = request.POST.get('semester_tahun'),



        )
        return HttpResponseRedirect("/form/")

    context = {
        'page_title':'Add course',
        'post_form':post_form
    }

    return render(request,'form/create.html',context)

def viewpage(request):
    return render(request,'form/viewpage.html')

def delete(request, delete_id):
    try:
        jadwal_to_delete = PostModel.objects.get(id = delete_id)
        jadwal_to_delete.delete()
        return redirect('form:index')
    except:
        return redirect('form:index')

def matkuldetail(request, id_nama_matkul):
    nama_matkul = PostModel.objects.filter(id=id_nama_matkul).get()
    response = {
        'page_title':'Detail Course',
        'nama_matkul':nama_matkul
    }
    
    return render(request, 'form/matkuldetail.html',response)

form/templates/form/create.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% block page_title %}
    {{page_title}}
{% endblock page_title %}
{% endblock meta %}


{% block content %}
<div class="container-fluid" style="text-align:justify;">
    <h1 style="font-family: 'Manuale', serif;">Add a course</h1>
    <form method="POST">
        {% csrf_token %}
        <table style="font-family: 'Manuale', serif; background-color: #E8E8E8 ;">
            {{post_form.as_table}}
        </table>
        <table class="center" style="font-family: 'Manuale', serif; background-color: #E8E8E8 ;">
            
            <tbody>
            <td>
                <button type="Submit">Send</button>
            </td>
            </tbody>
        </table>    
    </form>

</div>
{% endblock content %}

form/templates/form/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% block page_title %}
    {{page_title}}
{% endblock page_title %}
{% endblock meta %}


{% block content %}
<div class="container-fluid" style="text-align:justify;">
    <h1 style="font-family: 'Manuale', serif;">{{page_title}}</h1>

    <table style="font-family: 'Manuale', serif;" class="table">
        <thead>
            <tr>
                <th scope="col">Nama Mata Kuliah</th>
                <th scope="col">Jumlah SKS</th>
                <th scope="col">Ruangan</th>
                <th scope="col">Nama Dosen</th>
                <th scope="col">Deskripsi</th>
                <th scope="col">Semester Tahun</th>
                <th scope="col">Delete</th>


            </tr>
        </thead>
        <tbody>
            {%for post in posts %}
            <tr>
                <td><a href="{% url 'form:matkuldetail' post.id %}">{{post.nama_matkul}}</a></td>                
                <td>{{post.jumlah_sks}}</td>
                <td>{{post.ruangan}}</td>
                <td>{{post.dosen}}</td>
                <td>{{post.deskripsi}}</td>
                <td>{{post.semester_tahun}}</td>
                <td>
                    <a href="{% url 'form:delete' post.id %}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
</div>
{% endblock content %}

form/templates/form/matkuldetail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
{% block page_title %}
    {{page_title}}
{% endblock page_title %}
{% endblock meta %}

{% block content %}
<div class="container-fluid" style="text-align:justify;">
    <h1 style="font-family: 'Manuale', serif;">{{page_title}}</h1>


<div class="card">
    <div style="background-color:#cdc9c383; " class="card-header rounded-t-lg">
        <h1 style="font-family: 'Manuale', serif;" class="text-uppercase text-center">{{nama_matkul.nama_matkul}}</h1>
    </div>
    <div style="font-family: 'Manuale', serif;background-color:#fbf7f0;" class=" card-body">
        <table class="table">
            <tbody>
                <tr>
                    <td style="border-right: 2px solid black;" class="font-weight-bolder px-4 py-2">Jumlah SKS
                    </td>
                    <td class="text-sm-justify px-4 py-2">{{nama_matkul.jumlah_sks}}</td>
                </tr>
                <tr>
                    <td style="border-right: 2px solid black;" class="font-weight-bolder px-4 py-2">Ruangan
                    </td>
                    <td class="text-sm-justify px-4 py-2">{{nama_matkul.ruangan}}</td>
                </tr>
                <tr>
                    <td style="border-right: 2px solid black;" class="font-weight-bolder px-4 py-2">Dosen
                    </td>
                    <td class="text-sm-justify px-4 py-2">{{nama_matkul.dosen}}</td>
                </tr>
                <tr>
                    <td style="border-right: 2px solid black;" class="font-weight-bolder px-4 py-2">Deskripsi
                        matkul</td>
                    <td class="w-100 text-sm-justify px-4 py-2">{{nama_matkul.deskripsi}}</td>
                </tr>
                <tr>
                    <td style="border-right: 2px solid black;" class="font-weight-bolder px-4 py-2">Semester
                    </td>
                    <td class="text-sm-justify px-4 py-2">{{nama_matkul.semester_tahun}}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>


<div class="flex-1 text-gray-700 text-center  py-2 m-2 ">
    <div class="rounder-lg ">
        <a class="btn btn-primary btn-lg" href="/form/" role="button">Back to the list</a>
    </div>
</div>
{% endblock content %}

form/templates/form/viewpage.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
<div class="container-fluid">
    <div class="jumbotron">
        <h1 style="font-family: 'Manuale', serif;" class="display-4">My Courses</h1>
        <p class="lead">Hello, You can add new course or see the list of existing courses
        </p>
        <hr class="my-4">
        <p>If you want to add a new course, choose the Add a course one else choose the other</p>
        <a class="btn btn-primary btn-lg" href="/form/create" role="button">Add a course</a>
        <a class="btn btn-primary btn-lg" href="/form/" role="button">See the list</a>
    </div>

</div>
{% endblock content %}